name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "Readme.md"

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continous integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code
        run: echo "Linting repository"

      - name: unit test
        run: echo "Unit testing"

  build-and-push-docker-image:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todoapp:${{ github.sha }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: nikhilp047/gitops-infra
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "poojarynikhil047@gmail.com"
          git config --global user.name "nikhilp047"
          echo ${{ github.sha }}
          sed -i "s#${{ secrets.DOCKERHUB_USERNAME}}.*#${{ secrets.DOCKERHUB_USERNAME }}/todoapp:${{ github.sha }}#g" dev/deployment.yaml
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main